#!/bin/sh
read -p "Enter the server ip address: " ip
echo "OK, starting now..."
cd config
sftp root@$ip <<EOF
cd /home/yours/shared/config
put app_credentials
put apple_push_notification.pem
put photo_bucket_name
put ssl/server.crt ssl
put ssl/server.key ssl
bye
EOF
