#!/bin/sh
read -p "Enter the server ip address: " ip
echo "OK, starting now..."
cd config
sftp root@$ip <<EOF
mkdir -p /home/yours/shared/config
cd /home/yours/shared/config
put app_credentials
put apple_push_notification.pem
put photo_bucket_name
mkdir /etc/nginx/ssl
put ssl/server.crt /etc/nginx/ssl
put ssl/server.key /etc/nginx/ssl
bye
EOF
